# Generated by Django 3.2.19 on 2023-12-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_submission_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
